ifast:
  projectName: ifast
  projectRootURL: http://ifast.site/
  demoMode: false
  jwt:
    userPrimaryKey: userId
    expireTokenKeyPrefix: ifast:expireToken
    expireTime: 7200000
    refreshTokenExpire: 86400000
  swagger:
    title: ifast接口文档
    description: 开发人员太懒，没有写描述
    contactName: Aron
    contactEmail: izenglong@163.com
    contactUrl: http://ifast.site/doc.html
  shiro:
    jsessionidKey: SESSION
    sessionKeyPrefix: ifast:session
  oss:
    # local.localPath本地上传（正式环境可使用绝对路径），aliyun.accessKeySecret阿里云上传，两个都注释则使用七牛云上传（sys_config.oss_qiniu）
    local:
      localPath: /upload
      rootURL: http://ifast.site/upload
    aliyun:
      accessKeyId: 
      #accessKeySecret:
      bucketName: 
      # endpoint以深圳为例，其它region请按实际情况填写
      endpoint: http://oss-cn-shenzhen.aliyuncs.com      
  sms:
    cacheKey: ifast:cache
    cacheKeyPrefix: sms
    codeExpireTime: 900
    zt:
      uname: UNAME
      passwd: PASSWD
      productId: PRODUCT_ID
      scenes:
        validCode: 验证码{code}，您正在进行身份验证，打死也不要告诉别人哦！
    # 使用aliyun发送短信时请注释zt.passwd，配置accessKeyId和accessKeySecret，添加配置表项sys_config.sms_aliyun_validCode
    aliyun:
      accessKeyId: 
      #accessKeySecret: 
      scenes:
        # 配置格式为包含SignName和TemplateCode的json字符串：sys_config.sms_aliyun_validCode = {SignName, TemplateCode}
        validCode: sms_aliyun_validCode
logging:
  level:
    com.ifast: info
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ifast?useUnicode=true&useSSL=false
    connectionInitSqls: SET NAMES utf8mb4;
    username: root
    password: 1024key@root
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
